input {
  file {
    path => "/logs/*.log"
    start_position => "beginning"
    codec => "json"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "todo-logs"
  }
}
